### ISSUE TITLE
Code Testing

### ISSUE THREAD

**Issue by floridop** [WGDino/MNXB01ProjectE#33]
Hi Team E,

I checked your code and here are the results. 
These tests where done at commit b4009e00f8e27c417b9d76744a62c1755dd1aeaf

### Pros:

- README.md is present. It attempts to describe how to run most of the code.
- Changelog and Workplan adequate.

### Cons:

- Code is untestable. Reasons below.

- Setting up the code requires a lot of manual editing of the code 
itself. It is quite overwhelming and time consuming to correct and use.
The instructions try to help but I really could not understand exactly
what to do for each and every result. This should be done by a computer,
not by a human. See final remarks.
  - References in the instructions are quite vague. 
    - What is "the third and fourth command in the section xxx" in README.md
      line 18. Shall I count commands starting from 0 or from 1? I could
      not test all the combinations.
    - What would be the "specific times" in README.md line 25? I did not
      want to remove any.
    - I do not understand README.md line 26 at all.
    - Whenever you say in README.md "move script" I would suggest you
      just create a script for us to test. We are not supposed to
      change or write your code.

- The folder structure inside `code/` is not explained anywhere. The
  authors seems to assume the reader should guess how it works. I kind of
  assumed every folder is a project, but then I am required to move files
  around and edit source, and that's where it gets very confusing.

- I tried to run the skeleton by just changing the include folder but it
fails. Exceptions are not used and no validation is done which causes the
  code to crash badly on bad input. I did not understand exactly what to 
  comment and what not. I don't see why I should tamper your code 
  to run it anyway, except for the obvious include folders.
  
```console
[pflorido@aurora-rviz01 Skeleton]$ root
   ------------------------------------------------------------
  | Welcome to ROOT 6.10/02                http://root.cern.ch |
  |                               (c) 1995-2017, The ROOT Team |
  | Built for linuxx8664gcc                                    |
  | From tag v6-10-02, 6 July 2017                             |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q' |
   ------------------------------------------------------------

Info in <TUnixSystem::ACLiC>: creating shared library /home/pflorido/MNXB01-2021/projects/E/MNXB01ProjectE/Code/Skeleton/./src/tempTrender_cpp.so
In file included from input_line_11:9:
././src/tempTrender.cpp:23:19: error: out-of-line definition of 'tempOnDay' does not match any declaration in
      'tempTrender'
void tempTrender::tempOnDay(int monthToCalculate, int dayToCalculate...
                  ^~~~~~~~~
././src/tempTrender.cpp:76:19: error: out-of-line definition of 'tempOnDay' does not match any declaration in
      'tempTrender'
void tempTrender::tempOnDay(int dateToCalculate) const {  //Make a hi...
                  ^~~~~~~~~
././src/tempTrender.cpp:179:19: error: out-of-line definition of 'extremetemps' does not match any declaration in
      'tempTrender'
void tempTrender::extremetemps(string year){ 
                  ^~~~~~~~~~~~
Error in <ACLiC>: Dictionary generation failed!
```

- I tried to run `root` and `.L` some `.C` file in each result directory, but since no instructions where given
on how to use those I got lost. I am no ROOT or C++ expert and none of these scripts provided any
`project()` functions.
  
### Other remarks

- I refuse to test this code. At the current status is not runable for 
me, as I am required to do too many steps to make it work, which means
I am actually fixing your code. I cannot evaluate my own work as yours.
I leave it to other teachers to decide how to evaluate this.

- In this project, it is you that has to write code, not the teachers.

- The idea of writing code is to limit the things a user has to do on the
code itself. It would have been better to provide a cleaner script
for each result since you did not even copy pasted code that was
provided for similar purposes during the course.

Please provide appropriate cleaning scripts, code and instructions for each result in
each result folder. Please provide a sample data input one can test on. This will make things look better.

**Comment by WGDino** [comment]
Updates/Fixes:
removed old directories for individual results since they all now reside inside skeleton
Integrated individual cleaners into the skeleton for each result which require no tampering
Included more callable functions in the project.cpp so the only chnage for each new user is the include folder path in rootlogon.C

**Comment by floridop** [comment]
Thanks a lot, I was about to write to you. I will retest as soon as possible.

**Comment by EinarElen** [comment]
Realized that this probably deserved a separate issue so moved my feedback there

**Comment by floridop** [comment]
Quick update at commit 3aa46e5cecccd52ec7bc52bcb26180cdf13186bd
I will not perform further tests
 
- Cleaner() gives no output about what is doing, but it seems it did stuff. Would be nice to tell the user what's going on if you write something like this in the future.

- Good job with updating the Skeleton and Readme, now it is very good.
